package com.grievance.grievance_system.service;

import com.grievance.grievance_system.dto.AiAnalysisResponse;
import com.grievance.grievance_system.dto.ComplaintRequest;
import com.grievance.grievance_system.entity.*;
import com.grievance.grievance_system.exception.ResourceNotFoundException;
import com.grievance.grievance_system.repository.ComplaintHistoryRepository;
import com.grievance.grievance_system.repository.ComplaintRepository;
import com.grievance.grievance_system.repository.DepartmentRepository;
import com.grievance.grievance_system.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class ComplaintService {

    private final ComplaintRepository complaintRepository;
    private final ComplaintHistoryRepository complaintHistoryRepository;
    private final UserRepository userRepository;
    private final DepartmentRepository departmentRepository;
    private final AiFallbackService aiFallbackService;

    public ComplaintService(
            ComplaintRepository complaintRepository,
            ComplaintHistoryRepository complaintHistoryRepository,
            UserRepository userRepository,
            DepartmentRepository departmentRepository,
            AiFallbackService aiFallbackService
    ) {
        this.complaintRepository = complaintRepository;
        this.complaintHistoryRepository = complaintHistoryRepository;
        this.userRepository = userRepository;
        this.departmentRepository = departmentRepository;
        this.aiFallbackService = aiFallbackService;
    }

    @Transactional
    public Complaint submitComplaint(String userEmail, ComplaintRequest request) {
        User citizen = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // 1. Send to AI for Analysis
        AiAnalysisResponse analysis = aiFallbackService.getAnalysis(request.getDescription());

        // 2. Department Routing
        Department department = departmentRepository.findByName(analysis.getDepartment())
                .orElseGet(() -> {
                    // Create unmapped departments on the fly for demo purposes, 
                    // or route to a Default department.
                    Department newDept = Department.builder()
                            .name(analysis.getDepartment())
                            .description("Generated by AI routing")
                            .build();
                    return departmentRepository.save(newDept);
                });

        // 3. Save Complaint
        Complaint complaint = Complaint.builder()
                .user(citizen)
                .description(request.getDescription())
                .category(analysis.getCategory())
                .priority(analysis.getPriority())
                .department(department)
                .status(Status.PENDING)
                .build();

        Complaint savedComplaint = complaintRepository.save(complaint);

        // 4. Save Status History
        ComplaintHistory history = ComplaintHistory.builder()
                .complaint(savedComplaint)
                .status(Status.PENDING)
                .remarks("Complaint submitted and analyzed by AI.")
                .build();

        complaintHistoryRepository.save(history);

        return savedComplaint;
    }

    public List<Complaint> getAllComplaints() {
        return complaintRepository.findAllByOrderByCreatedAtDesc();
    }

    public List<Complaint> getComplaintsByUser(String email) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
        return complaintRepository.findByUserId(user.getId());
    }

    public Complaint getComplaintById(Long id) {
        return complaintRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Complaint not found: " + id));
    }

    public List<ComplaintHistory> getComplaintTracking(Long id) {
        if (!complaintRepository.existsById(id)) {
            throw new ResourceNotFoundException("Complaint not found: " + id);
        }
        return complaintHistoryRepository.findByComplaintIdOrderByUpdatedAtDesc(id);
    }

    @Transactional
    public Complaint updateComplaintStatus(Long id, Status newStatus, String remarks) {
        Complaint complaint = getComplaintById(id);
        complaint.setStatus(newStatus);

        if (newStatus == Status.RESOLVED) {
            complaint.setResolvedAt(LocalDateTime.now());
        }

        Complaint updatedComplaint = complaintRepository.save(complaint);

        ComplaintHistory history = ComplaintHistory.builder()
                .complaint(updatedComplaint)
                .status(newStatus)
                .remarks(remarks)
                .build();
        complaintHistoryRepository.save(history);

        return updatedComplaint;
    }
}
